spring:
  application:
    name: bicycle-allocation
server:
  port: 8082
  servlet:
    context-path: /bicycle-allocation-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true