server:
  port: 8085
  servlet:
    context-path: /bicycle-allocation-api
spring:
  application:
    name: bicycle-allocation
  datasource:
    url: jdbc:postgresql://localhost:5432/bicycle_workspace
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bicycle_allocation
    show-sql: false
  flyway:
    default-schema: bicycle_allocation
  rabbitmq:
    username: admin
    password: admin
    host: localhost
    port: 5672
#    addresses: localhost:5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    preferIpAddress: true