spring:
  application:
    name: client-register
server:
  port: 8083
  servlet:
    context-path: /client-register-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
