spring:
  application:
    name: bicycle-register
server:
  port: 8081
  servlet:
    context-path: /bicycle-register-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true