server:
  port: 8081
  servlet:
    context-path: /bicycle-register-api
spring:
  application:
    name: bicycle-register
  datasource:
    url: jdbc:postgresql://localhost:5432/bicycle_workspace
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bicycle_register
    show-sql: false
  flyway:
    default-schema: bicycle_register
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    preferIpAddress: true